// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sports News App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        {/* ▼▼▼ 1. ヘッダー (全ページ共通) ▼▼▼ */}
        <header className="bg-blue-600 text-white p-4 shadow-md">
          <div className="max-w-6xl mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">
              <Link href="/">⚽ Sports News</Link>
            </h1>
            <nav>
              <Link href="/news" className="hover:text-blue-200 underline">
                ニュース一覧
              </Link>
            </nav>
          </div>
        </header>

        <div className="flex flex-1 max-w-6xl mx-auto w-full">
          {/* ▼▼▼ 2. サイドバー (全ページ共通) ▼▼▼ */}
          <aside className="w-64 bg-gray-100 p-6 hidden md:block border-r">
            <h3 className="font-bold text-gray-700 mb-4">メニュー</h3>
            <ul className="space-y-2 text-sm text-gray-600">
              <li>
                <Link href="/" className="hover:text-blue-600 block">ホーム</Link>
              </li>
              <li>
                <Link href="/news" className="hover:text-blue-600 block">最新ニュース</Link>
              </li>
              <li>未定</li>
            </ul>
          </aside>

          {/* ▼▼▼ 3. メインコンテンツ (ページごとに変わる部分) ▼▼▼ */}
          <main className="flex-1 p-6 bg-white">
            {children}
          </main>
        </div>

        {/* フッター */}
        <footer className="bg-gray-800 text-white text-center p-4 text-sm">
          何書くか未定
        </footer>
      </body>
    </html>
  );
}